package com.law.lawlens09

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import android.widget.TextView
import kotlin.random.Random

class TipActivity : AppCompatActivity() {

    private val lawTips = listOf(
        "Always get everything in writing.",
        "Know the laws that apply to your case.",
        "Be honest with your lawyer.",
        "Understand your contract before signing.",
        "Document all interactions.",
        "Keep copies of all legal documents.",
        "Don’t hesitate to ask questions.",
        "Respect the legal process.",
        "Be aware of your rights.",
        "Stay organized.",
        "Stay informed about changes in law.",
        "Consult a lawyer for legal advice.",
        "Do not sign documents you don’t understand.",
        "Research the legal precedents relevant to your case.",
        "Be punctual in legal matters.",
        "Understand the Indian Penal Code (IPC) sections relevant to you.",
        "Know the procedures for filing an FIR.",
        "Maintain confidentiality in sensitive legal matters.",
        "Understand your obligations under contracts.",
        "Seek legal aid if you cannot afford a lawyer.",
        "Respect court orders and procedures.",
        "Know the rights provided under the Constitution.",
        "Understand the role of different courts in India.",
        "Stay calm and composed in legal proceedings.",
        "Report crimes immediately to authorities.",
        "Participate in jury duty if called upon.",
        "Know the legal implications of social media usage.",
        "Be aware of the legal age for marriage.",
        "Understand the legal procedures for divorce.",
        "Be informed about consumer rights and laws.",
        "Know the process of obtaining a passport.",
        "Respect intellectual property laws.",
        "Be aware of anti-corruption laws.",
        "Know your rights in case of arrest.",
        "Understand the legalities of property transactions.",
        "Be aware of cyber laws and online safety.",
        "Understand the importance of evidence in legal cases.",
        "Know the laws regarding defamation.",
        "Be aware of traffic rules and regulations.",
        "Understand the laws regarding domestic violence.",
        "Know the legal age for voting.",
        "Understand the procedures for filing a PIL (Public Interest Litigation).",
        "Know your rights regarding workplace harassment.",
        "Be aware of laws protecting minority rights.",
        "Understand the legal aspects of starting a business.",
        "Respect environmental laws.",
        "Know the legal requirements for adoption.",
        "Be informed about your rights as a tenant.",
        "Understand the process for obtaining citizenship.",
        "Know the laws regarding child labor.",
        "Be aware of laws related to drug abuse.",
        "Understand the importance of a legal will.",
        "Respect privacy laws.",
        "Be aware of the laws regarding abortion.",
        "Know the legal procedures for inheritance.",
        "Understand the laws related to medical negligence.",
        "Be aware of animal rights laws.",
        "Understand the legal implications of breaking quarantine.",
        "Know the rights of disabled persons.",
        "Be informed about senior citizens' legal rights.",
        "Understand the legal aspects of online transactions.",
        "Be aware of anti-discrimination laws.",
        "Know the laws regarding noise pollution.",
        "Understand the legalities of self-defense.",
        "Be aware of the laws protecting whistleblowers.",
        "Know the legal procedures for changing your name.",
        "Understand the laws regarding financial fraud.",
        "Be aware of human rights laws.",
        "Know the procedures for legal guardianship.",
        "Understand the laws related to public protests.",
        "Be aware of the legal implications of euthanasia.",
        "Know the laws regarding illegal detention.",
        "Understand the legalities of charitable donations.",
        "Be informed about the legal rights of refugees.",
        "Know the laws regarding racial discrimination.",
        "Understand the legalities of organ donation.",
        "Be aware of laws protecting victims of crime.",
        "Know the legal aspects of consumer protection.",
        "Understand the laws regarding cyberbullying.",
        "Be informed about labor laws and workers' rights.",
        "Know the legal procedures for dealing with debt.",
        "Understand the laws related to online privacy.",
        "Be aware of the legal aspects of environmental conservation.",
        "Know the procedures for filing a legal complaint.",
        "Understand the laws regarding workplace safety.",
        "Be aware of the legal rights of indigenous people.",
        "Know the laws regarding human trafficking.",
        "Understand the legal implications of forgery.",
        "Be aware of the laws protecting intellectual freedom.",
        "Know the legal aspects of educational rights.",
        "Understand the laws related to financial scams.",
        "Be informed about the legal rights of artists.",
        "Know the laws regarding marriage registration.",
        "Understand the legalities of foreign exchange.",
        "Be aware of the laws protecting women's rights.",
        "Know the legal procedures for reporting child abuse.",
        "Understand the laws related to bankruptcy.",
        "Be informed about the legal rights of patients.",
        "Know the laws regarding sexual harassment.",
        "Understand the legal implications of insider trading.",
        "Be aware of the laws regarding online defamation."
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_tip)

        val tipTextView: TextView = findViewById(R.id.tipTextView)
        val randomTip = lawTips[Random.nextInt(lawTips.size)]
        tipTextView.text = randomTip
    }
}
